### PR TITLE
Initial PR

### PR DESCRIPTION
**Pull request by andrasguseo**
https://central.tri.be/issues/114513

### CODE REVIEW

**Review by cliffordp — DISMISSED** [review]
- [ ] Delete `README.md`
- [ ] Delete `LICENSE`
- [ ] Replace `array()` with `[]` (optional)
- [ ] Replace `tribe-common` text domains with `tribe-ext-custom-all-events-url` text domain
- [ ] Fix typo in Description: `Allows the definition OF a custom...`
- [ ] Do not include `edit.php?post_type=tribe_events&page=tribe-common` in Description, since that may not be everyone's same URL, and do not have this linked in this plain text area (plugin header and readme). Use [plugin_action_links()](https://developer.wordpress.org/reference/hooks/plugin_action_links/) if you want to add a URL
- [ ] A) The `Enter your custom URL, including` text should not have escaped single quotes in it. Either wrap in single quote and use double-quotes within text or vice-versa. B) This string has HTML in it but is wrapped in `esc_html__()`. It's ideal not to have HTML in translatable strings.
- [ ] Regenerate `.pot` file

**Comment by cliffordp** [comment]
@andrasguseo please resolve the conflicts before I can review

**Comment by andrasguseo** [comment]
@cliffordp 
> Replace array() with [] (optional)

I tried this and I always got an error: Parse error: syntax error, unexpected '[', expecting '(' in /app/public/wp-content/plugins/tribe-ext-custom-all-events-url/src/Tribe/Settings_Helper.php on line 68
Please point out where exactly this needs to be changed.

>please resolve the conflicts before I can review

I tried my best with my limited git experience and only manage to mess up my local repo. No clue what to do / how to do. Please walk me through it.

**Comment by cliffordp** [comment]
@andrasguseo I made changes for you, as requested in Slack DM. Also see Central ticket question.

**Comment by andrasguseo** [comment]
@cliffordp not sure how do deal with resolving the conflicts. Last time I tried everything got messed up.

**Comment by cliffordp** [comment]
@andrasguseo 

Sorry for the delay getting back to you.

I found these via command line:
* tribe-ext-custom-all-events-url.php deleted in HEAD and modified in initial
* src/Tribe/Settings_Helper.php deleted in HEAD and modified in initial
* readme.txt deleted in HEAD and modified in initial
* languages/tribe-ext-custom-all-events-url.pot deleted in HEAD and modified in initial

So I just added them directly to Master branch and then everything was okay for this PR.

Feel free to continue on or to ask for more help.

You might want to use the Namespaces and Autoloading from the [latest update to the extension template](https://github.com/mt-support/tribe-ext-extension-template) for this, since it uses the Settings Helper.

**Pull request merged**
